print("Por favor pense em um numero")
input("e Tecle <enter>")
print("Multiplique este numero por 6")
input("e Tecle <enter>")
print("Divida-o por 2")
input("e Tecle <enter>")
print("Some o resultado com o valor 9")
input("e Tecle <enter>")
print("Divida o resultado por 3")
input("e Tecle <enter>")
print("Subtraia do numero que você havia pensado")
input("e Tecle <enter>")
print("O resultado deu 3")

