print("Pense em um numero")
input("e tecle <enter>")
print("Some com 2")
input("e tecle <enter>")
print("Multiplique por 6")
input("e tecle <enter>")
print("Divida o numero por 2")
input("e tecle <enter>")
print("Multiplique por 3")
input("e tecle <enter>")
print("Divida por 9")
input("e tecle <enter>")
print("Subtraia do numero que voce pensou")
input("e tecle <enter>")
print("Multiplique o resultado por 3")
input("e tecle <enter>")
print("Resultado sera o numero 6")